# Generated by Django 3.2.5 on 2021-07-02 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_userslots_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslots',
            name='det_of_slot',
            field=models.DateField(default=datetime.date(2021, 7, 2)),
        ),
        migrations.AlterField(
            model_name='userslots',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userslots',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
